### ISSUE TITLE
Opening Lab does not result in fork this Lab being checked

### ISSUE THREAD

**Issue by MysticRiver** [learn-co-curriculum/html-issue-bot-9000#4]
When I click on open this lab it does not automatically result in the Fork this Lab button being checked. SO even though My code is right It does not allow me to advance to the next lesson.

also You need to tell students to type Learn submit at the end of every lesson so that they submit the pull request.

**Comment by matbalez** [comment]
Hi @MysticRiver we're looking into why your Fork light didn't get flipped to green. 

Also, re: instructing students to type `learn submit` I'm not sure actually. I think it would be really repetitive to continuously describe that workflow on every code lab. That's why we walk you through the full workflow early on in the Intro to Learn track a couple of times. Perhaps, the first few labs in the curriculum should re-inforce it then we drop it. @pletcher @AnnJohn thoughts?

**Comment by pletcher** [comment]
@matbalez @MysticRiver Apologies for the delay -- I was out the end of last week.

I agree with that flow, @matbalez -- I'll go back and add reinforcement to the first few lessons, and then hopefully by this stage students can be comfortable seeing "submit" and thinking "`learn submit`".

Does that seem right?

**Comment by matbalez** [comment]
SGTM

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
